apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-210305-90zq-service
spec:
  selector:
    app: enterprise-system-210305-90zq
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
